version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch-node-browsers-legacy

    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:0e:09:d0:2e:50:1c:ef:54:25:43:2e:54:76:56:36"
      - run:
          name: Install dependencies
          command: |
            cd ~
            wget https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
            sudo dpkg -i hugo*.deb
            hugo version
      - checkout
      - run:
          name: Checkout the submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
            cd public
            git checkout master
            cd ..
      - run:
          name: Build site from source
          command: hugo
      - run:
          name: Deploy site
          command: |
            git config --global user.email "spaghettiwews@outlook.com"
            git config --global user.name "spaghettiwews"
            cd public
            git add .
            msg="rebuilding site `date`"
            if [ $# -eq 1 ]
              then msg="$1"
            fi
            git commit -m "$msg"
            git push origin master
      - run:
          name: Update public submodule
          command: |
            ls
            git submodule update --remote
            git status
            git add .
            git commit -m "update public submodule `date`"
            git push origin master
