name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{ secrets.THEME_TOKEN }}
    - name: Install hugo
      run: |
        echo "installing hugo"
        sudo mkdir -p /home/hugo/
        curl -L https://github.com/gohugoio/hugo/releases/download/v0.59.0/hugo_0.59.0_Linux-64bit.tar.gz | tar -zxf - --directory /home/hugo/
        sudo mv /home/hugo/hugo /usr/bin/
    - name: Build site
      env:
        SOURCE_DIRECTORY: bookmarks/
      run: |
        echo $PWD
        ls
        #cd $SOURCE_DIRECTORY
        hugo --verbose
    - name: Deploy compiled site (commit and push to GH Pages repo)
      env:
        OUTPUT_DIRECTORY: public/
      run: |
        cd $OUTPUT_DIRECTORY
        git status
